# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Memetic Musings
tagline:          'A blog on computing'
description:      'Life long learner. Eclectic. Likes to read, code, play badminton.'
url:              http://amitdev.github.io

author:
  name:           'Amit'
  url:            https://twitter.com/amitdevr

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/amitdev

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
